# Generated by Django 3.2.3 on 2021-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='rejected',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='resolved',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
